# Generated by Django 3.1 on 2020-08-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='career_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_objective', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='exam_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination', models.CharField(max_length=50)),
                ('Board_university', models.CharField(max_length=100)),
                ('Institute', models.CharField(max_length=100)),
                ('Year_of_passing', models.IntegerField()),
                ('cgpa_percentage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_Address', models.CharField(max_length=256)),
                ('DOB', models.DateField()),
                ('Hobbies', models.CharField(max_length=256)),
                ('Languages', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Father_name', models.CharField(max_length=30)),
                ('Mother_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='female', max_length=10)),
                ('City', models.CharField(max_length=256)),
                ('State', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=30)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
