# Generated by Django 3.1 on 2020-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='permanent_Address',
            field=models.TextField(),
        ),
    ]
